//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAuth.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinAuth.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About WinAuth ähnelt.
        /// </summary>
        internal static string _AboutForm_ {
            get {
                return ResourceManager.GetString("_AboutForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WinAuth {0}
        ///Copyright {1}. Colin Mackie. All rights reserved. ähnelt.
        /// </summary>
        internal static string _AboutForm_aboutLabel_ {
            get {
                return ResourceManager.GetString("_AboutForm_aboutLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string _AboutForm_closeButton_ {
            get {
                return ResourceManager.GetString("_AboutForm_closeButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License ähnelt.
        /// </summary>
        internal static string _AboutForm_licenseLabel_ {
            get {
                return ResourceManager.GetString("_AboutForm_licenseLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diagnostics... ähnelt.
        /// </summary>
        internal static string _AboutForm_reportButton {
            get {
                return ResourceManager.GetString("_AboutForm_reportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battle.net, World of Warcraft, StarCraft, Diablo, Mists of Pandaria, and all associated logos and designs are trademarks or registered trademarks of Blizzard Entertainment.
        ///
        ///NCsoft, the interlocking NC logo, ArenaNet, Guild Wars, Guild Wars Factions, Guild Wars Nightfall, Guild Wars: Eye of the North, Guild Wars 2, and all associated logos and designs are trademarks or registered trademarks of NCsoft Corporation.
        ///
        ///Valve, the Valve logo, Half-Life, the Half-Life logo, the Lambda logo, Steam, the Steam lo [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string _AboutForm_trademarkLabel_ {
            get {
                return ResourceManager.GetString("_AboutForm_trademarkLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protection ähnelt.
        /// </summary>
        internal static string _ChangePasswordForm_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string _ChangePasswordForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select how you would like to protect your authenticators. Using a password is strongly recommended, otherwise your data could be read and stolen by malware running on your computer. ähnelt.
        /// </summary>
        internal static string _ChangePasswordForm_introLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_introLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encrypt to only be useable on this computer ähnelt.
        /// </summary>
        internal static string _ChangePasswordForm_machineCheckbox_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_machineCheckbox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additionally, you can protect and encrypt your data using the built-in Windows account encryption. This will lock your authenticators to this computer or user so they cannot be opened even if the files are copied. You MUST turn this off if you are going to reformat your disk, re-install Windows or delete this user account. ähnelt.
        /// </summary>
        internal static string _ChangePasswordForm_machineLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_machineLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string _ChangePasswordForm_okButton_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protect with my own password ähnelt.
        /// </summary>
        internal static string _ChangePasswordForm_passwordCheckbox_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_passwordCheckbox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string _ChangePasswordForm_passwordFieldLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_passwordFieldLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your authenticators will be encrypted using your own password and you will need to enter your password to open WinAuth. Your authenticators will be inaccessible if you forget your password and you do not have a backup. ähnelt.
        /// </summary>
        internal static string _ChangePasswordForm_passwordLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_passwordLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die And only by the current user on this computer ähnelt.
        /// </summary>
        internal static string _ChangePasswordForm_userCheckbox_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_userCheckbox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verify ähnelt.
        /// </summary>
        internal static string _ChangePasswordForm_verifyFieldLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_verifyFieldLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WinAuth Error ähnelt.
        /// </summary>
        internal static string _ExceptionForm_ {
            get {
                return ResourceManager.GetString("_ExceptionForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue ähnelt.
        /// </summary>
        internal static string _ExceptionForm_continueButton_ {
            get {
                return ResourceManager.GetString("_ExceptionForm_continueButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Details ähnelt.
        /// </summary>
        internal static string _ExceptionForm_detailsButton_ {
            get {
                return ResourceManager.GetString("_ExceptionForm_detailsButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error has occured in WinAuth.
        ///
        ///{0}
        ///
        ///Some diagnostic information has been recorded and saved that might help track down issues in WinAuth.
        ///
        ///It would help if you can submit this information so we can investigate the crash and try and fix the issue. This information does include information about your authenticators but is only used by the WinAuth developers solely for the purpose of investigating bugs and error reports. It does not include any personal or identifying information. Any information sent [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string _ExceptionForm_errorLabel_ {
            get {
                return ResourceManager.GetString("_ExceptionForm_errorLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        /// </summary>
        internal static string _ExceptionForm_quitButton_ {
            get {
                return ResourceManager.GetString("_ExceptionForm_quitButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send Error Report ähnelt.
        /// </summary>
        internal static string _ExceptionForm_reportButton_ {
            get {
                return ResourceManager.GetString("_ExceptionForm_reportButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter Password ähnelt.
        /// </summary>
        internal static string _GetPasswordForm_ {
            get {
                return ResourceManager.GetString("_GetPasswordForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string _GetPasswordForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_GetPasswordForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string _GetPasswordForm_okButton_ {
            get {
                return ResourceManager.GetString("_GetPasswordForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die password ähnelt.
        /// </summary>
        internal static string _GetPasswordForm_passwordField_ {
            get {
                return ResourceManager.GetString("_GetPasswordForm_passwordField_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PGP Key ähnelt.
        /// </summary>
        internal static string _GetPGPKeyForm_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse... ähnelt.
        /// </summary>
        internal static string _GetPGPKeyForm_browseButton_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_browseButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Or, select your key file ähnelt.
        /// </summary>
        internal static string _GetPGPKeyForm_browseLabel_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_browseLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string _GetPGPKeyForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid password ähnelt.
        /// </summary>
        internal static string _GetPGPKeyForm_invalidPassword_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_invalidPassword_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string _GetPGPKeyForm_okButton_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optional password ähnelt.
        /// </summary>
        internal static string _GetPGPKeyForm_passwordField_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_passwordField_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If your key has a password ähnelt.
        /// </summary>
        internal static string _GetPGPKeyForm_passwordLabel_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_passwordLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter or select your PGPkey ähnelt.
        /// </summary>
        internal static string _GetPGPKeyForm_pgpLabel_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_pgpLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Password ähnelt.
        /// </summary>
        internal static string _SetPasswordForm_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string _SetPasswordForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string _SetPasswordForm_okButton_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string _SetPasswordForm_passwordField_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_passwordField_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a password to protect this authenticator or leave blank to remove it ähnelt.
        /// </summary>
        internal static string _SetPasswordForm_setPasswordLabel_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_setPasswordLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show ähnelt.
        /// </summary>
        internal static string _SetPasswordForm_showCheckbox_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_showCheckbox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verify ähnelt.
        /// </summary>
        internal static string _SetPasswordForm_verifyField_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_verifyField_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shortcut Key ähnelt.
        /// </summary>
        internal static string _SetShortcutKeyForm_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die more info ähnelt.
        /// </summary>
        internal static string _SetShortcutKeyForm_advancedLink_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_advancedLink_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced... ähnelt.
        /// </summary>
        internal static string _SetShortcutKeyForm_advancedRadioButton_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_advancedRadioButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;strong&gt;Advanced&lt;/strong&gt;
        ///&lt;p&gt;You can use a mixture of text and commands to build up your string to be sent to your application.&lt;/p&gt;
        ///&lt;ul&gt;&lt;li&gt;{CODE} inserts the current code&lt;/li&gt;
        ///&lt;li&gt;{ENTER delay repeat} to send the ENTER key with optional delay in seconds and repeat count&lt;/li&gt;
        ///&lt;li&gt;{TAB  delay repeat} to send the TAB key&lt;/li&gt;
        ///&lt;li&gt;{COPY} to copy the code into the clipboard&lt;/li&gt;
        ///&lt;li&gt;{PASTE} to paste the clipboard contents into the active window&lt;/li&gt;
        ///&lt;li&gt;{EXIT} to exit WinAuth.&lt;/li&gt;&lt;/ul&gt;
        ///&lt;p&gt;For example,  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string _SetShortcutKeyForm_advancedTextbox_tooltip {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_advancedTextbox_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string _SetShortcutKeyForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter code into current window or one called... ähnelt.
        /// </summary>
        internal static string _SetShortcutKeyForm_injectRadioButton_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_injectRadioButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a shortcut key and action ähnelt.
        /// </summary>
        internal static string _SetShortcutKeyForm_introLabel_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_introLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key ähnelt.
        /// </summary>
        internal static string _SetShortcutKeyForm_keyLabel_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_keyLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show a notification ähnelt.
        /// </summary>
        internal static string _SetShortcutKeyForm_notifyRadioButton_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_notifyRadioButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string _SetShortcutKeyForm_okButton_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy code to the clipboard ähnelt.
        /// </summary>
        internal static string _SetShortcutKeyForm_pasteRadioButton_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_pasteRadioButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string _UnprotectPasswordForm_ {
            get {
                return ResourceManager.GetString("_UnprotectPasswordForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string _UnprotectPasswordForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_UnprotectPasswordForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string _UnprotectPasswordForm_okButton_ {
            get {
                return ResourceManager.GetString("_UnprotectPasswordForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string _UnprotectPasswordForm_passwordField_ {
            get {
                return ResourceManager.GetString("_UnprotectPasswordForm_passwordField_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string _WinAuthForm_addAuthenticatorButton_ {
            get {
                return ResourceManager.GetString("_WinAuthForm_addAuthenticatorButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click the &quot;Add&quot; button to create or import your authenticator ähnelt.
        /// </summary>
        internal static string _WinAuthForm_introLabel_ {
            get {
                return ResourceManager.GetString("_WinAuthForm_introLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string _WinAuthForm_passwordButton_ {
            get {
                return ResourceManager.GetString("_WinAuthForm_passwordButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string _WinAuthForm_passwordLabel_ {
            get {
                return ResourceManager.GetString("_WinAuthForm_passwordLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} is already running. ähnelt.
        /// </summary>
        internal static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authenticator not implemented ähnelt.
        /// </summary>
        internal static string AuthenticatorNotImplemented {
            get {
                return ResourceManager.GetString("AuthenticatorNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning: unable to connect to {0} to set time correctly.
        ///
        ///Your code may not be correct ähnelt.
        /// </summary>
        internal static string AuthenticatorSyncError {
            get {
                return ResourceManager.GetString("AuthenticatorSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Refresh ähnelt.
        /// </summary>
        internal static string AutoRefresh {
            get {
                return ResourceManager.GetString("AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to find your configuration file ähnelt.
        /// </summary>
        internal static string CannotFindConfigurationFile {
            get {
                return ResourceManager.GetString("CannotFindConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to load authenticator from {0} ähnelt.
        /// </summary>
        internal static string CannotLoadAuthenticator {
            get {
                return ResourceManager.GetString("CannotLoadAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change or Remove Password ähnelt.
        /// </summary>
        internal static string ChangeOrRemovePassword {
            get {
                return ResourceManager.GetString("ChangeOrRemovePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to copy to the clipboard. Another application is probably using it.
        ///
        ///Try again? ähnelt.
        /// </summary>
        internal static string ClipboardInUse {
            get {
                return ResourceManager.GetString("ClipboardInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your authenticators were saved with newer a version of WinAuth and so cannot be loaded. Please use WinAuth {0} or later. ähnelt.
        /// </summary>
        internal static string ConfigIsNewer {
            get {
                return ResourceManager.GetString("ConfigIsNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WinAuth has upgraded your authenticators to version {0}.
        ///
        ///Do NOT run an older version of WinAuth as this could overwrite them.
        ///
        ///Now is a good time to make a backup. Click the Options icon and choose Export. ähnelt.
        /// </summary>
        internal static string ConfigUpgraded {
            get {
                return ResourceManager.GetString("ConfigUpgraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirmations ähnelt.
        /// </summary>
        internal static string ConfirmTrades {
            get {
                return ResourceManager.GetString("ConfirmTrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Code ähnelt.
        /// </summary>
        internal static string CopyCode {
            get {
                return ResourceManager.GetString("CopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy on New Code ähnelt.
        /// </summary>
        internal static string CopyOnNewCode {
            get {
                return ResourceManager.GetString("CopyOnNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action ähnelt.
        /// </summary>
        internal static string DefaultAction {
            get {
                return ResourceManager.GetString("DefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy To Clipboard ähnelt.
        /// </summary>
        internal static string DefaultActionCopyToClipboard {
            get {
                return ResourceManager.GetString("DefaultActionCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simulate Hotkey ähnelt.
        /// </summary>
        internal static string DefaultActionHotkey {
            get {
                return ResourceManager.GetString("DefaultActionHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Notification ähnelt.
        /// </summary>
        internal static string DefaultActionNotification {
            get {
                return ResourceManager.GetString("DefaultActionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete this authenticator?
        ///
        ///This will permanently remove it and you may no longer be able to access you account. ähnelt.
        /// </summary>
        internal static string DeleteAuthenticatorWarning {
            get {
                return ResourceManager.GetString("DeleteAuthenticatorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a password ähnelt.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error loading image file: {0}
        ///
        ///Do you want to try again? ähnelt.
        /// </summary>
        internal static string ErrorLoadingIconFile {
            get {
                return ResourceManager.GetString("ErrorLoadingIconFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error has occurred ähnelt.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you. Your error report has been submitted. ähnelt.
        /// </summary>
        internal static string ErrorReportSubmitted {
            get {
                return ResourceManager.GetString("ErrorReportSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to send your error report ähnelt.
        /// </summary>
        internal static string ErrorSendingErrorReport {
            get {
                return ResourceManager.GetString("ErrorSendingErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File must be a zip file ähnelt.
        /// </summary>
        internal static string FileMustBeZip {
            get {
                return ResourceManager.GetString("FileMustBeZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Details ähnelt.
        /// </summary>
        internal static string HideDetails {
            get {
                return ResourceManager.GetString("HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The shortuct key combination is already in use or not available ähnelt.
        /// </summary>
        internal static string HotKeyNotAvailable {
            get {
                return ResourceManager.GetString("HotKeyNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon ähnelt.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
        /// </summary>
        internal static string IconAuto {
            get {
                return ResourceManager.GetString("IconAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error importing at line {0}:{1} ähnelt.
        /// </summary>
        internal static string ImportError {
            get {
                return ResourceManager.GetString("ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid authenticator at line {0} ähnelt.
        /// </summary>
        internal static string ImportInvalidUri {
            get {
                return ResourceManager.GetString("ImportInvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid password ähnelt.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Icon Image ähnelt.
        /// </summary>
        internal static string LoadIconImage {
            get {
                return ResourceManager.GetString("LoadIconImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have an authenticator from a previous version of WinAuth ({0}).
        ///
        ///You can either import it now or use the &apos;Add&apos; button to import it later.
        ///
        ///Would you like to import your previous authenticator now? ähnelt.
        /// </summary>
        internal static string LoadPreviousAuthenticator {
            get {
                return ResourceManager.GetString("LoadPreviousAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always on Top ähnelt.
        /// </summary>
        internal static string MenuAlwaysOnTop {
            get {
                return ResourceManager.GetString("MenuAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Size ähnelt.
        /// </summary>
        internal static string MenuAutoSize {
            get {
                return ResourceManager.GetString("MenuAutoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Protection ähnelt.
        /// </summary>
        internal static string MenuChangeProtection {
            get {
                return ResourceManager.GetString("MenuChangeProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export... ähnelt.
        /// </summary>
        internal static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import... ähnelt.
        /// </summary>
        internal static string MenuImportText {
            get {
                return ResourceManager.GetString("MenuImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import WinAuth 2.x ähnelt.
        /// </summary>
        internal static string MenuImportWinauth {
            get {
                return ResourceManager.GetString("MenuImportWinauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portable ähnelt.
        /// </summary>
        internal static string MenuPortable {
            get {
                return ResourceManager.GetString("MenuPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember Position ähnelt.
        /// </summary>
        internal static string MenuRememberPosition {
            get {
                return ResourceManager.GetString("MenuRememberPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start With Windows ähnelt.
        /// </summary>
        internal static string MenuStartWithWindows {
            get {
                return ResourceManager.GetString("MenuStartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for updates... ähnelt.
        /// </summary>
        internal static string MenuUpdates {
            get {
                return ResourceManager.GetString("MenuUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use System Tray Icon ähnelt.
        /// </summary>
        internal static string MenuUseSystemTrayIcon {
            get {
                return ResourceManager.GetString("MenuUseSystemTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select or enter a file ähnelt.
        /// </summary>
        internal static string MissingFile {
            get {
                return ResourceManager.GetString("MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a PGP key ähnelt.
        /// </summary>
        internal static string MissingPGPKey {
            get {
                return ResourceManager.GetString("MissingPGPKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other ähnelt.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} already exists.
        ///
        ///Do you want to overwrite it? ähnelt.
        /// </summary>
        internal static string OverwritePortableConfigFile {
            get {
                return ResourceManager.GetString("OverwritePortableConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwords do not match ähnelt.
        /// </summary>
        internal static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename ähnelt.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Password ähnelt.
        /// </summary>
        internal static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shortcut Key ähnelt.
        /// </summary>
        internal static string ShortcutKey {
            get {
                return ResourceManager.GetString("ShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Code ähnelt.
        /// </summary>
        internal static string ShowCode {
            get {
                return ResourceManager.GetString("ShowCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show SteamGuard and Recovery Code ähnelt.
        /// </summary>
        internal static string ShowRevocation {
            get {
                return ResourceManager.GetString("ShowRevocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Secret Key ähnelt.
        /// </summary>
        internal static string ShowSecretKey {
            get {
                return ResourceManager.GetString("ShowSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Serial &amp;&amp; Restore Code ähnelt.
        /// </summary>
        internal static string ShowSerialAndRestoreCode {
            get {
                return ResourceManager.GetString("ShowSerialAndRestoreCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Serial Key and Device ID ähnelt.
        /// </summary>
        internal static string ShowSerialKeyAndDeviceId {
            get {
                return ResourceManager.GetString("ShowSerialKeyAndDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sync Time ähnelt.
        /// </summary>
        internal static string SyncTime {
            get {
                return ResourceManager.GetString("SyncTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unknown error occured ähnelt.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For the best security it is recommended that you upgrade Microsoft .Net to version 4.5.
        ///
        ///Would you like to go to the Microsoft .Net download page (open your browser)? ähnelt.
        /// </summary>
        internal static string UpgradeDotNet {
            get {
                return ResourceManager.GetString("UpgradeDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please insert your YubiKey or press the flashing button ähnelt.
        /// </summary>
        internal static string YubikeyInsert {
            get {
                return ResourceManager.GetString("YubikeyInsert", resourceCulture);
            }
        }
    }
}
